module.exports = [
    {
        prefix: "Prof.",
        firstName: "Reiner Jun",
        middleName: "Gepayo",
        lastName: "Alminaza",
        suffix: "",
        position: "Assistant Professor IV",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Adrian",
        middleName: "C.",
        lastName: "Alumbro",
        suffix: "",
        position: "Instructor II",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Gilbert",
        middleName: "Amor",
        lastName: "Amistas",
        suffix: "",
        position: "Part - Time Instructor",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Anelyn",
        middleName: "Piano",
        lastName: "Anas",
        suffix: "",
        position: "Associate Professor II",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Agustin",
        middleName: "Nuñez",
        lastName: "Arceña",
        suffix: "",
        position: "Associate Professor II",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Tommy",
        middleName: "Mahilum",
        lastName: "Artajo",
        suffix: "",
        position: "Assistant Professor II",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Rey",
        middleName: "Maghari",
        lastName: "Arturo",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Rosabeth",
        middleName: "Mana-ay",
        lastName: "Arturo",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Ivony",
        middleName: "Simpas",
        lastName: "Asprilla",
        suffix: "",
        position: "Assistant Professor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Alvin Erick",
        middleName: "Casinillo",
        lastName: "Bales",
        suffix: "",
        position: "Instructor II",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Sol",
        middleName: "Montaño",
        lastName: "Basañes",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Alfred John",
        middleName: "Gallo",
        lastName: "Borreros",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "",
        firstName: "Julie Jane",
        middleName: "Gallo",
        lastName: "Borreros",
        suffix: "",
        position: "Intructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Jean",
        middleName: "Gabales",
        lastName: "Bullo",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Jocyl",
        middleName: "Chavez",
        lastName: "Caber",
        suffix: "",
        position: "Associate Professor II",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Joven",
        middleName: "Camarista",
        lastName: "Cablas",
        suffix: "",
        position: "Assistant Professor IV",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Bernardo",
        middleName: "Gaviola",
        lastName: "Cagasan",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Simeon",
        middleName: "Juaca",
        lastName: "Cainday",
        suffix: "",
        position: "Assistant Professor III",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Conrado",
        middleName: "Salinas",
        lastName: "Calumpita",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Geraldo",
        middleName: "Bedan",
        lastName: "Cang",
        suffix: "",
        position: "Assistant Professor IV",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "April Rose",
        middleName: "Sumalapao",
        lastName: "Cantua",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Kissy",
        middleName: "Gabinete",
        lastName: "Cariaga",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Eric",
        middleName: "Palmos",
        lastName: "Catalan",
        suffix: "",
        position: "Assistant Professor IV",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Ruby",
        middleName: "Durban",
        lastName: "Catalan",
        suffix: "",
        position: "Associate Professor V",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Allan",
        middleName: "Sendico",
        lastName: "David",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Josephine",
        middleName: "GULAYLAY",
        lastName: "De Asis",
        suffix: "",
        position: "Associate Professor III",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Margie",
        middleName: "Yucon",
        lastName: "De la Cruz",
        suffix: "",
        position: "Associate Professor IV",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Sheila Mae",
        middleName: "Artajo",
        lastName: "Diaz",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Criste",
        middleName: "Ferrer",
        lastName: "Dilag",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Erwin",
        middleName: "Dela",
        lastName: "Dumagpi",
        suffix: "",
        position: "Associate Professor IV",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "French Marie",
        middleName: "Palcullo",
        lastName: "Edang",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Lovely Joy",
        middleName: "Jacome",
        lastName: "Egael",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Jasmine",
        middleName: "Cadornigara",
        lastName: "Eguilos",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Marin Dexter",
        middleName: "Laab",
        lastName: "Ejar",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Ana",
        middleName: "Pastolero",
        lastName: "Encarquez",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Aizle",
        middleName: "Fuenres",
        lastName: "Eres",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Antonieta",
        middleName: "Salinas",
        lastName: "Espin",
        suffix: "",
        position: "Assistant Professor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Aziel Lyn",
        middleName: "Ymalay",
        lastName: "Estilo",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Jufel",
        middleName: "Del Rosario",
        lastName: "Fernandez",
        suffix: "",
        position: "Assistant Professor II",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Rhea Joy",
        middleName: "Descalso",
        lastName: "Flora",
        suffix: "",
        position: "Assistant Professor II",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Adrian",
        middleName: "Jaleco",
        lastName: "Forca",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "James Ryan",
        middleName: "Balictar",
        lastName: "Ga",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Adora",
        middleName: "Bartizo",
        lastName: "Gabayoyo",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Jonathan",
        middleName: "Gabion",
        lastName: "Gabion",
        suffix: "",
        position: "Associate Professor V",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Joeve Grace",
        middleName: "Natividad",
        lastName: "Gaborno",
        suffix: "",
        position: "Part Time Instructor",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Jasmin",
        middleName: "Taasan",
        lastName: "Gadian",
        suffix: "",
        position: "Associate Professor I",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Elizabeth",
        middleName: "G.",
        lastName: "Gajo",
        suffix: "",
        position: "Assistant Professor III",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Frenz Rian",
        middleName: "Garcia",
        lastName: "Gal",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Revenlie",
        middleName: "Gadnanan",
        lastName: "Galapin",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Loveson",
        middleName: "Catoltol",
        lastName: "Gallos",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Fermin",
        middleName: "Beboso",
        lastName: "Galve",
        suffix: "",
        position: "Assistant Professor I",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Gerald Sheo Thon",
        middleName: "Daquipil",
        lastName: "Gamo",
        suffix: "",
        position: "Assistant Professor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Beverly",
        middleName: "Faeldan",
        lastName: "Garmay",
        suffix: "",
        position: "Instructor III",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Ronald",
        middleName: "Gello-ani",
        lastName: "Gentapanan",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Jo Ann",
        middleName: "Tejada",
        lastName: "Gerada",
        suffix: "",
        position: "Instructor III",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Niel John",
        middleName: "Martir",
        lastName: "Gonzales",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Ruben",
        middleName: "Monton",
        lastName: "Habaña",
        suffix: "",
        position: "Assistant Professor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Reynro",
        middleName: "Tumangan",
        lastName: "Herrera",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Ralph",
        middleName: "Pama",
        lastName: "Hervilla",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Daisy",
        middleName: "Buenconsejo",
        lastName: "Ibieza",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Ervin",
        middleName: "Labestre",
        lastName: "Isogon",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Elishama Jepphunee",
        middleName: "Dunton",
        lastName: "Isogon",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Anthony",
        middleName: "Pecasiosa",
        lastName: "Jalando-On",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Anelyn",
        middleName: "Acebuche",
        lastName: "Janaban",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Joel",
        middleName: "Vergara",
        lastName: "Japitana",
        suffix: "",
        position: "Associate Professor V",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Aser",
        middleName: "M.",
        lastName: "Job",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Ethel",
        middleName: "Pagot",
        lastName: "Junco",
        suffix: "",
        position: "Associate Professor II",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Reynald",
        middleName: "Torres",
        lastName: "Ladera",
        suffix: "",
        position: "Associate Professor IV",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Fernando",
        middleName: "Jaminillo",
        lastName: "Libutaque",
        suffix: "",
        position: "Associate Professor II",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Donnavie",
        middleName: "Dominguez",
        lastName: "Loriezo",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Jimmy",
        middleName: "P.",
        lastName: "Luzuriaga",
        suffix: "",
        position: "Assistant Professor IV",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Jeffrey",
        middleName: "Gallego",
        lastName: "Magbanua",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Ellyn Ly",
        middleName: "O.",
        lastName: "Maramento",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Nenen",
        middleName: "Nequin",
        lastName: "Marquez",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "",
        firstName: "Clarisse",
        middleName: "Rea",
        lastName: "Marte",
        suffix: "",
        position: "Part Time Faculty",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Erly",
        middleName: "M.",
        lastName: "Martir",
        suffix: "",
        position: "Associate Professor II",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Rodney",
        middleName: "Narisma",
        lastName: "Martires",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Mary Joy",
        middleName: "Tercena",
        lastName: "Molate",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Rome",
        middleName: "Bayoging",
        lastName: "Moralista",
        suffix: "",
        position: "Associate Professor III",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Katherine",
        middleName: "Legita",
        lastName: "Niego",
        suffix: "",
        position: "Assistant Professor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Agatha Rica",
        middleName: "Barbero",
        lastName: "Norilla",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Michael",
        middleName: "Mucho",
        lastName: "Occeña",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Rodrigo",
        middleName: "Gomilla",
        lastName: "Paglomutan",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Andrew",
        middleName: "Decosto",
        lastName: "Paguntalan",
        suffix: "",
        position: "Assistant Professor II",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Kyrl",
        middleName: "Sartorio",
        lastName: "Palma",
        suffix: "",
        position: "Associate Professor II",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Norie",
        middleName: "Habaña",
        lastName: "Palma",
        suffix: "",
        position: "Associate Professor V",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Shiela Mae",
        middleName: "Grate",
        lastName: "Paltiguera",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Jasmin",
        middleName: "Lemana",
        lastName: "Parreño",
        suffix: "",
        position: "Associate Professor V",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Methusela",
        middleName: "Clemente",
        lastName: "Perrocha",
        suffix: "",
        position: "Associate Professor V",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Kert",
        middleName: "Dolido",
        lastName: "Pillora",
        suffix: "",
        position: "Associate Professor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Ferick Brenz",
        middleName: "Pahilagao",
        lastName: "Porras",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Joebert Diane",
        middleName: "Concepcion",
        lastName: "Ramos",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Nelson",
        middleName: "Jarlega",
        lastName: "Rodriguez",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Kristine",
        middleName: "Gonzales",
        lastName: "Rosero",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Roger",
        middleName: "Biñas",
        lastName: "Rueda",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Jerry",
        middleName: "Homena",
        lastName: "Salinas",
        suffix: "",
        position: "Instructor III",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Ana Liza",
        middleName: "Gallego",
        lastName: "Sanchez",
        suffix: "",
        position: "Assistant Professor II",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Joedar",
        middleName: "Palerit",
        lastName: "Satojito",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "",
        firstName: "Vivian",
        middleName: "Andaya",
        lastName: "Segobre",
        suffix: "",
        position: "Part-Time",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Enriqueta",
        middleName: "Nabajo",
        lastName: "Siva",
        suffix: "",
        position: "Associate Professor V",
        gender: "F",
    },
    {
        prefix: "Prof.",
        firstName: "Mona Liza",
        middleName: "Habaña",
        lastName: "Sollano",
        suffix: "",
        position: "Professor III",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Arthur",
        middleName: "Cantores",
        lastName: "Soqueña",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Maychelle",
        middleName: "Pelaez",
        lastName: "Sorongon",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Salem John",
        middleName: "Paris",
        lastName: "Suelon",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Maribeth",
        middleName: "Esguerra",
        lastName: "Sumalde",
        suffix: "",
        position: "Assistant Professor IV",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Liezel",
        middleName: "Andaluz",
        lastName: "Tabale",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Divon",
        middleName: "Galampanao",
        lastName: "Tamdang",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Efren",
        middleName: "Salcedo",
        lastName: "Tellermo",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Leopoldo Third",
        middleName: "Rodriguez",
        lastName: "Tumapang",
        suffix: "",
        position: "Instructor III",
        gender: "M",
    },
    {
        prefix: "Prof.",
        firstName: "Julius",
        middleName: "Tagabuhin",
        lastName: "Vergara",
        suffix: "",
        position: "Assistant Professor IV",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Helen",
        middleName: "Roque",
        lastName: "Vilbar",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Rodante",
        middleName: "Ganila",
        lastName: "Villaflor",
        suffix: "",
        position: "Instructor I",
        gender: "M",
    },
    {
        prefix: "Instr.",
        firstName: "Ma. Xy",
        middleName: "Juanillo",
        lastName: "Yanguas",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    },
    {
        prefix: "Instr.",
        firstName: "Lea",
        middleName: "Pelaez",
        lastName: "Ymalay",
        suffix: "",
        position: "Instructor I",
        gender: "F",
    }
]