//// Core modules

//// External modules

//// Modules


module.exports = [
    // Admin
    {
        "prefix": "Dr.",
        "firstName" : "Norie",
        "middleName" : "H.",
        "lastName" : "Palma",
        "suffix" : "",
        "position" : "Associate Professor V",
        "gender" : "F",
        "birthDate" : null,
    },
    {
        "prefix": "Dr.",
        "firstName" : "Enriqueta",
        "middleName" : "N.",
        "lastName" : "Siva",
        "suffix" : "",
        "position" : "Associate Professor V",
        "gender" : "F",
        "birthDate" : null,
    },
    {
        "prefix": "Dr.",
        "firstName" : "Methusela",
        "middleName" : "C.",
        "lastName" : "Perrocha",
        "suffix" : "",
        "position" : "Associate Professor V",
        "gender" : "F",
        "birthDate" : null,
    },
    {
        "prefix": "Dr.",
        "firstName" : "Mona Liza",
        "middleName" : "H.",
        "lastName" : "Sollano",
        "suffix" : "",
        "position" : "Professor III",
        "gender" : "F",
        "birthDate" : null,
    },
    {
        "prefix": "Dr.",
        "firstName" : "Jonathan",
        "middleName" : "G.",
        "lastName" : "Gabion",
        "suffix" : "",
        "position" : "Associate Professor V",
        "gender" : "M",
        "birthDate" : null,
    },
    {
        "prefix": "Dr.",
        "firstName" : "Jocyl",
        "middleName" : "C.",
        "lastName" : "Caber",
        "suffix" : "",
        "position" : "Associate Professor II",
        "gender" : "F",
        "birthDate" : null,
    },
    {
        "prefix": "Dr.",
        "firstName" : "Joel",
        "middleName" : "V.",
        "lastName" : "Japitana",
        "suffix" : "",
        "position" : "Associate Professor V",
        "gender" : "M",
        "birthDate" : null,
    },
    {
        "prefix": "Dr.",
        "firstName" : "Jasmin",
        "middleName" : "T.",
        "lastName" : "Gadian",
        "suffix" : "",
        "position" : "Associate Professor I",
        "gender" : "F",
        "birthDate" : null,
    },
    {
        "prefix": "Dr.",
        "firstName" : "Ruby",
        "middleName" : "D.",
        "lastName" : "Catalan",
        "suffix" : "",
        "position" : "Assistant Professor IV",
        "gender" : "F",
        "birthDate" : null,
    },
    {
        "prefix": "Dr.",
        "firstName" : "Joedar",
        "middleName" : "P.",
        "lastName" : "Satojito",
        "suffix" : "",
        "position" : "Instructor I",
        "gender" : "F",
        "birthDate" : null,
    },
    {
        "prefix": "Dr.",
        "firstName" : "Sol",
        "middleName" : "M.",
        "lastName" : "Basañes",
        "suffix" : "",
        "position" : "Instructor I",
        "gender" : "F",
        "birthDate" : null,
    },
    {
        "prefix": "Prof.",
        "firstName" : "Josephine",
        "middleName" : "G.",
        "lastName" : "De Asis",
        "suffix" : "",
        "position" : "Associate Professor III",
        "gender" : "F",
        "birthDate" : null,
    },
    {
        "prefix": "Instr.",
        "firstName" : "John Israel",
        "middleName" : "G",
        "lastName" : "Tagudin",
        "suffix" : "",
        "position" : "Instructor I",
        "gender" : "M",
        "birthDate" : null,
    },
    {
        "prefix": "Instr.",
        "firstName" : "Jeffrey",
        "middleName" : "G.",
        "lastName" : "Magbanua",
        "suffix" : "",
        "position" : "Instructor I",
        "gender" : "M",
        "birthDate" : null,
    },
    {
        "prefix": "Instr.",
        "firstName" : "Aziel Lyn",
        "middleName" : "Y.",
        "lastName" : "Estilo",
        "suffix" : "",
        "position" : "Instructor III",
        "gender" : "F",
        "birthDate" : null,
    },
    {
        "prefix": "Prof.",
        "firstName" : "Khristian",
        "middleName" : "T.",
        "lastName" : "de la Rama",
        "suffix" : "",
        "position" : "Assistant Professor I",
        "gender" : "M",
        "birthDate" : null,
    },
    {
        "prefix": "Instr.",
        "firstName" : "Amelia Fe",
        "middleName" : "G.",
        "lastName" : "Adin",
        "suffix" : "",
        "position" : "Part-time Instructor",
        "gender" : "F",
        "birthDate" : null,
    },
    {
        "prefix": "Instr.",
        "firstName" : "Joebert Diane",
        "middleName" : "C.",
        "lastName" : "Ramos",
        "suffix" : "",
        "position" : "Instructor I",
        "gender" : "M",
        "birthDate" : null,
    },
    {
        "prefix": "Instr.",
        "firstName" : "Gilbert",
        "middleName" : "A.",
        "lastName" : "Amistas",
        "suffix" : "",
        "position" : "Instructor I",
        "gender" : "M",
        "birthDate" : null,
    },
    
]