module.exports = [
    {
        name: 'Bachelor of Science in Agriculture',
        code: 'BSA',
        version: '',
        campus: 'BAT',
        active: true,
        collegeId: 1,
        hasBoard: true,
    },
    {
        name: 'Bachelor of Science in Fisheries',
        code: 'BSF',
        version: '',
        campus: 'BAT',
        active: true,
        collegeId: 1,
        hasBoard: true,
    },
    {
        name: 'Bachelor of Arts in English Language Studies',
        code: 'BAEL',
        version: '',
        campus: 'SAL',
        active: true,
        collegeId: 2,
    },
    {
        name: 'Bachelor of Public Administration',
        code: 'BPA',
        version: '',
        campus: 'SAL',
        active: true,
        collegeId: 2,
    },
    {
        name: 'Bachelor of Science in Business Administration',
        code: 'BSBA',
        version: '',
        campus: 'SAL',
        active: true,
        hasMajor: true,
        collegeId: 3,
    },
    {
        name: 'Bachelor of Science in Entrepreneurship',
        code: 'BSEntrep',
        version: '',
        campus: 'SAL',
        active: true,
        collegeId: 3,
    },
    {
        name: 'Bachelor of Science in Hospitality Management',
        code: 'BSHM',
        version: '',
        campus: 'SAL',
        active: true,
        collegeId: 8,
    },
    {
        name: 'Bachelor of Science in Real Estate Management',
        code: 'BSREM',
        version: '',
        campus: 'SAL',
        active: true,
        collegeId: 3,
    },
    {
        name: 'Bachelor of Science in Tourism Management',
        code: 'BSTM',
        version: '',
        campus: 'SAL',
        active: true,
        collegeId: 8,
    },
    // 
    {
        name: 'Bachelor of Science in Criminology',
        code: 'BSCrim',
        version: '',
        campus: 'SAL',
        active: true,
        collegeId: 4,
        hasBoard: true,
    },
    // 
    {
        name: 'Bachelor of Industrial Technology',
        code: 'BIT',
        version: '',
        campus: 'SAL',
        active: true,
        collegeId: 5,
        hasMajor: true,
    },
    {
        name: 'Bachelor of Science in Electrical Engineering',
        code: 'BSEE',
        version: '',
        campus: 'SAL',
        active: true,
        collegeId: 5,
        hasBoard: true,
    },
    {
        name: 'Bachelor of Science in Mechanical Engineering',
        code: 'BSME',
        version: '',
        campus: 'SAL',
        active: true,
        collegeId: 5,
        hasBoard: true,
    },
    // 
    {
        name: 'Bachelor of Science in Information Technology',
        code: 'BSIT',
        version: '',
        campus: 'MOS',
        active: true,
        collegeId: 6,
    },
    {
        name: 'Bachelor of Science in Computer Science',
        code: 'BSCS',
        version: '',
        campus: 'MOS',
        active: true,
        collegeId: 6,
    },
    {
        name: 'Bachelor of Science in Information Systems',
        code: 'BSIS',
        version: '',
        campus: 'MOS',
        active: true,
        collegeId: 6,
    },
    {
        name: 'Bachelor of Science in Food Technology',
        code: 'BSFT',
        version: '',
        campus: 'MOS',
        active: true,
        collegeId: 6,
    },
    // 
    {
        name: 'Bachelor of Elementary Education',
        code: 'BSEEd',
        version: '',
        campus: 'SAL',
        active: true,
        hasBoard: true,
        hasMajor: true,
        collegeId: 7,
    },
    {
        name: 'Bachelor of Secondary Education',
        code: 'BSEd',
        version: '',
        campus: 'SAL',
        active: true,
        hasBoard: true,
        hasMajor: true,
        collegeId: 7,
    },
    {
        name: 'Bachelor of Technology and Livelihood Education',
        code: 'BTLE',
        version: '',
        campus: 'SAL',
        active: true,
        hasMajor: true,
        collegeId: 7,
    },
    // Grad school
    {
        name: 'Master in Public Administration',
        code: 'MPA',
        version: '',
        campus: 'SAL',
        active: true,
        collegeId: 9,
    },
    {
        name: 'Master in Education',
        code: 'MaEd',
        version: '',
        campus: 'SAL',
        active: true,
        hasMajor: true,
        collegeId: 9,
    },
    {
        name: 'Master of Arts in Teaching Mathematics',
        code: 'MATM',
        version: '',
        campus: 'SAL',
        active: true,
        hasMajor: true,
        collegeId: 9,
    },
    {
        name: 'Master in Business Administration',
        code: 'MBA',
        version: '',
        campus: 'SAL',
        active: true,
        collegeId: 9,
    },
    {
        name: 'Doctor of Philosophy in Educational Management',
        code: 'PHD',
        version: '',
        campus: 'SAL',
        active: true,
        collegeId: 9,
    },
    {
        name: 'Doctor in Management',
        code: 'DMPM',
        version: '',
        campus: 'SAL',
        active: true,
        hasMajor: true,
        collegeId: 9,
    },
    {
        name: 'Doctor of Education in Curriculum and Instruction',
        code: 'EDD',
        version: '',
        campus: 'SAL',
        active: true,
        hasMajor: true,
        collegeId: 9,
    },
    
]
